openapi: "3.0.1"
info:
  title: "Customer"
  version: "1"
  description: Customer API
servers:
  - url: http://localhost:8080/api
    description: Customer API server
paths:
  /customer:
    post:
      summary: Save Customer
      operationId: saveCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'
  /customer/{id}:
    get:
      summary: GET Customer by id
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: Unique Id of each Customer
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'

components:
  schemas:
    CustomerDto:
      type: object
      description: Attributes of Customer
      required:
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
          minLength: 5
          maxLength: 50
        lastName:
          type: string
          minLength: 5
          maxLength: 50
    ErrorDto:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string